//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsandTravelSystem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripsandTravelesSystemEntities : DbContext
    {
        public TripsandTravelesSystemEntities()
            : base("name=TripsandTravelesSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<RatePosts> RatePosts { get; set; }
        public virtual DbSet<Saved> Saved { get; set; }
        public virtual DbSet<Travaler> Travaler { get; set; }
        public virtual DbSet<TripPost> TripPost { get; set; }
    }
}
