//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsandTravelSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatePosts
    {
        public int RateId { get; set; }
        public Nullable<bool> Like { get; set; }
        public Nullable<bool> DisLike { get; set; }
        public Nullable<int> Stars { get; set; }
        public int TravalerId { get; set; }
        public int PostId { get; set; }
    
        public virtual Travaler Travaler { get; set; }
        public virtual TripPost TripPost { get; set; }
    }
}
