//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsandTravelSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripPost()
        {
            this.RatePosts = new HashSet<RatePosts>();
            this.Saved = new HashSet<Saved>();
        }
    
        public int TripId { get; set; }
        public string TripTitle { get; set; }
        public string TripDetails { get; set; }
        public string PostDate { get; set; }
        public string TripDate { get; set; }
        public string TripDestination { get; set; }
        public int Price { get; set; }
        public string TripImage { get; set; }
        public string Status { get; set; }
        public int AgencyId { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatePosts> RatePosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saved> Saved { get; set; }
    }
}
